#spring:
#  datasource:
#    url: jdbc:sqlserver://pengumpultugasmbkm.database.windows.net:1433/pengumpultugasmbkm
#      username: CloudSAca14b355@pengumpultugasmbkm
#        password: root123@
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
#
#server:
#  port: 9191
#jdbc:sqlserver://pengumpultugasmbkm.database.windows.net:1433;database=pengumpultugasmbkm;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;